### ISSUE TITLE
Feature request: setting to to turn of scroll animation

### ISSUE THREAD

**Issue by mikez** [randy3k/Terminus#305]
Wow, what an awesome plugin, @randy3k! I'm so happy to have discovered this today. I love your attention to detail. The code is also a joy to browse.  ✨

A small request:
After hitting enter in the terminal, I'd enjoy it scroll to the end right away without animation.

Might we have a setting for that? :-)

I believe the crucial code is [here](https://github.com/randy3k/Terminus/blob/811ff55392910574f57c983f5c52ea0e74864353/terminus/render.py#L262). The setting would let the second argument here be `False`.

What do you think?

**Comment by randy3k** [comment]
Yes, it is the correct setting.

**Comment by mikez** [comment]
I would like you to hear me differently.

Right now, Terminus scrolls with an animation to the bottom, that is, `view.set_viewport_position((0, y), True)`.

I would enjoy a custom setting in the `Terminus.sublime-settings` that also lets us disable that animation. With this custom setting, the code instead runs:
`view.set_viewport_position((0, y), False)`

**Comment by anthroid** [comment]
If this is request is to provide a setting to disable the "smooth scrolling" animation that occurs when lines are output from the terminal, I agree that a setting to turn this off (and have immediate, non-animated, line-by-line scrolling output like iTerm, Terminal.app, VS Code, Terminator, etc) would be ideal. Especially if it is as simple as passing `False` instead of `True` as determined by @mikez.
