### ISSUE TITLE
Resizing Window Columns - Text Disappears

### ISSUE THREAD

**Issue by divingskyward** [randy3k/Terminus#32]
When layout columns are resized on Ubuntu 16.04 and macOS Mojave, text disappears until there's interaction with the terminal. Below are images of the issue on Ubuntu 16.04 and ST v3.1.1 Build 3176. Steps to reproduce are 1) create or add a column, 2) run commands in terminal to generate text, 3) resize the column so that text is obscured, 4) resize and expect text to show again, 5) press arrow key up and run command again and text appears. This is particularly difficult to deal with when running a long command while trying to view its text stream.

![image](https://user-images.githubusercontent.com/31905271/43734940-272991fe-996e-11e8-8a18-a2e55179176e.png)
![image](https://user-images.githubusercontent.com/31905271/43735006-50c92a06-996e-11e8-8466-39c6a8f0d27c.png)
![image](https://user-images.githubusercontent.com/31905271/43734954-2e8d4aee-996e-11e8-8102-5e529fba3aa1.png)
![image](https://user-images.githubusercontent.com/31905271/43734958-326d13ec-996e-11e8-8f81-90483e1cbaf9.png)

**Comment by randy3k** [comment]
Thanks for the detailed reproducible steps.

Originally, text will be truncated when the width of the window is decreased. It may more sensible to keep the text to prevent data lost.

**Comment by divingskyward** [comment]
Thanks! Would be great to keep the text if possible.

**Comment by monkape** [comment]
@randy3k Reporting that this is still not fixed.

Your commit fixes text disappearing when resizing down  (and then scrolling in the downsized view), but when resizing back to a larger width the text disappears.

![fd](https://user-images.githubusercontent.com/23129307/82363078-a3b4aa00-9a0d-11ea-951c-7c44c1e0d44b.gif)

**Comment by randy3k** [comment]
@monkape actually the text is not truncated. There is a synchronization issue between the process and the screen. The text are not flowing correctly. It may be an upstream issue of winpty.

**Comment by monkape** [comment]
I see.

What do you think about adding a setting for minimum width ([take a look here](https://github.com/monkape/Terminus/commit/e550d83459b024f4820aebd868b34737c1570c42))? 

That fixes not only this problem, but also text wrapping when resizing a view that's running a never ending program, such as a web server.

before             |  after
:-------------------------:|:-------------------------:
![fsdsf](https://user-images.githubusercontent.com/23129307/82368912-77515b80-9a16-11ea-8c8f-75c9467a6ef3.gif)  |  ![fdsaf](https://user-images.githubusercontent.com/23129307/82368937-81735a00-9a16-11ea-954a-07bdd6492e38.gif)

I keep such terminals in groups to the right of the main view, and often resize them to a really small width in order to focus on the main content. Resizing back messes up the output + the noise from such programs can be distracting.

**Comment by randy3k** [comment]
I am happy to support such a setting, but I would set it the default to a smaller  number, say 20.

FYI, `word_wrap` is set as `false` in default.

**Comment by monkape** [comment]
> I am happy to support such a setting, but I would set it the default to a smaller number, say 20.

Great, I'll hit you up with a pull request.

> FYI, `word_wrap` is set as `false` in default.

I guess my wording was a bit off - what I meant was never "wrapping" the terminal content and not sublime's view.

It could be implemented by setting a huge width to the actual terminal (such that sublime's view won't surpass it) and then cropping lines (trimming whitespace) in view to match the longest line. That last bit is necessary to have a sensible horizontal scrollbar size.
